name: Deploy to GitHub Pages

on:
  repository_dispatch

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: update
      run: |
        cur=`pwd`
        mkdir themes
        cd $cur/themes && git clone https://github.com/jenkins-zh/hugo-jenkins-theme
        cd $cur/content && git clone https://github.com/jenkins-infra/wechat
        cd $cur/content/wechat/articles && rm sample.md && find . -name *.md -exec mv {} . \;
        rm -rf $cur/content/wechat/articles/2018
        rm -rf $cur/content/wechat/images/*.md
        rm -rf $cur/content/wechat/management/
        rm -rf $cur/content/wechat/*.md
    - name: hugo-deploy-gh-pages
      uses: jenkins-zh/hugo-gh-actions@v0.0.1
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        HUGO_VERSION: "0.53"
        WEBSITE_GIT: "git@github.com:jenkins-zh/jenkins-zh.github.io.git"
        WEBSITE_DIR: "jenkins-zh.github.io"